baseURL = 'http://axl2468.github.io/lapizote-personal/'
languageCode = 'en-us'
title = "Lapizote's Space"
theme = 'lappyMini'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true